### ISSUE TITLE
improve visuals

### ISSUE THREAD

**Issue by xenct** [AusClimateService/plotting_maps#19]
Some small tweaks to enhance the beauty of the plots:
 - remove logo
 - adjust default xlim and ylim
 - ensure figure is balanced well

![plotting_rainfall_anom_old](https://github.com/user-attachments/assets/afb8e739-0d28-41fc-bada-e1a10d34349b)

**Comment by xenct** [comment]
Example of new improved visuals.
- increase size of colourbar (cbar)
- centre watermark on Australia
- move title further the left edge
- remove erroneous space ion copywrite line
- adjust xlim and ylim to crop image tighter and include less ocean around land
- remove logo
- remove space between cbar label and cbar.
- move cbar closer to image and reduce blank space on right.

![plotting_rainfall_anom](https://github.com/user-attachments/assets/81a771b3-c842-4914-bf4c-2212be6cbdaa)

**Comment by stellema** [comment]
Is it possible to increase the dataset font size? It would be really helpful for comparing multi-model ensembles.

**Comment by xenct** [comment]
Hi @stellema , the plots can be made at a smaller figsize while keeping the text size the same (therefore the text size is proportionally larger). Would this address your query?

**Comment by stellema** [comment]
Yes, that helps. I've just been getting feedback that it doesn't stand out enough. For reference, here is an example of how it might look with a 1-2 size increase (I also increased the `baseline` font size for consistency). 

```import xarray as xr
import numpy as np
from acs_plotting_maps import plot_acs_hazard, regions_dict, cmap_dict

da = xr.DataArray(
    np.random.uniform(20, 65, (50, 60)),
    dims=["lat", "lon"],
    coords={"lat": np.arange(-45, 5), "lon": np.arange(110, 170)},
)
fs = 8
fig, ax = plot_acs_hazard(
    name="aus_states_territories",
    regions=regions_dict["aus_states_territories"],
    data=da,
    figsize=(8 * 0.8, 6 * 0.8),
    title=f"Dataset fontsize={fs}",
    date_range="1 July 1963 to 30 June 2028",
    cmap=cmap_dict["tasmax"],
    cbar_extend="neither",
    ticks=np.arange(20, 65, 5),
    tick_labels=None,
    cbar_label="Temperature [°C]",
    dataset_name="dataset",
    baseline="1963-2028",
    outfile=f"test_fs{fs}.png",
    mask_not_australia=True,
    xlim=(110, 170),
    ylim=(-45, -5),
    label_states=False,
    contourf=False,
    contour=False,
    select_area=None,
    land_shadow=True,
)
```

dataset and baseline `fontsize=6:`
![test_fs6](https://github.com/user-attachments/assets/711b6ae5-a1d3-4b30-8cbf-15ed775d26f4)

dataset and baseline `fontsize=7:`
![test_fs7](https://github.com/user-attachments/assets/4d4d18a8-b191-4667-b5ef-2f2d5dee4821)

dataset and baseline `fontsize=8:`
![test_fs8](https://github.com/user-attachments/assets/b789fd36-4a53-4eb1-970f-c7d52214abd5)
