### ISSUE TITLE
Logo path cannot be read remotely

### ISSUE THREAD

**Issue by xenct** [AusClimateService/plotting_maps#6]
The plotting script cannot read the ACS logo unless you are working within the plotting maps directory.
The logo's path needs to be updated so the script reads the absolute path of the logo file.
Until this is fixed, the whole module will not load if you're not in the plotting_maps directory.

**Comment by stellema** [comment]
This can be fixed using:

```
from pathlib import Path
logo = image.imread(Path(__file__).parent / "ACS_Logo_Blue_on_white_Stacked.png")
```

**Comment by xenct** [comment]
Thanks @stellema I have incorporated your fix and closed this issue
